version: '3.8'

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_anime_email-service
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GFGF18101961
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_anime_email-service
    restart: always
    ports:
      - "5051:81"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres