spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  mail:
    host: smtp.gmail.com
    port: 587
    username: 9197195@gmail.com
    password: suhjonzyinoerula
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082
  threads:
    virtual:
      enabled: true